### ISSUE TITLE
#Problem#Pull request

### ISSUE THREAD

**Issue by spattammadisajan** [bnajafi/TES_2019-2020_weeklySubmissions#183]
Dear Prof.
I have a problem with the pull request. I uploaded my file (week3 submission) and then I tried to pull request > new request but I could not find anything called 'create pull request' , it is showing as 'compare changes'.

What should I do? Your guidance will be really appreciated.
Also, I have attached a screenshot of the page for your reference.

![1](https://user-images.githubusercontent.com/56322380/67333188-6e4fe880-f520-11e9-9749-5bd9c8e99386.JPG)

Thanks in advance.

Regards,
Shayari Pattammadi Sajan

**Comment by mhajhashemi** [comment]
Dear Prof.
I have a problem with the pull request.  I can not upload  . what should i do                                                    hajhashemi.maryam

**Comment by bnajafi** [comment]
You are both trying to do the pill request in my page instead of your fork of the repository
